# Generated by Django 4.2.2 on 2023-07-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='appointed',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_text',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail_text',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
