# Generated by Django 4.0 on 2023-06-21 22:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='appointed',
            field=models.DateField(default=datetime.datetime(2023, 6, 21, 22, 49, 50, 511058, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='main_text',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
