# Generated by Django 4.0 on 2023-06-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_appointed_alter_event_main_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
