# Generated by Django 4.0 on 2023-06-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='appointed',
            field=models.DateTimeField(),
        ),
    ]
