# Generated by Django 4.2.2 on 2023-10-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img_url',
            field=models.URLField(blank=True, default='https://psycholebedenko-backend.s3.amazonaws.com/event_img_1.jpeg', null=True),
        ),
    ]
