# Generated by Django 4.2.2 on 2023-10-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img_url',
            field=models.URLField(blank=True, default='https://psycholebedenko-backend.s3.amazonaws.com/event_img_3.jpeg', null=True),
        ),
    ]
