# Generated by Django 4.2.2 on 2023-10-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_event_participants_limit_alter_event_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img_url',
            field=models.URLField(blank=True, default='https://psycholebedenko-backend.s3.amazonaws.com/event_img_3.jpeg', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
