# Generated by Django 4.2.2 on 2023-10-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_event_img_url_alter_event_participants_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img_url',
            field=models.URLField(blank=True, default='https://psycholebedenko-backend.s3.amazonaws.com/event_img_2.jpeg', null=True),
        ),
    ]
