# Generated by Django 4.2.2 on 2023-10-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psy_tests', '0005_alter_testresult_test_alter_testresult_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psycholytest',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
