FROM node:16-alpine 
WORKDIR /app
COPY package.json .
RUN npm ci 
COPY . .
ENV REACT_APP_BOT_NAME=Psycholebedenko_bot
ENV REACT_APP_BACKEND_URL=https://api.psycholebedenko.online
ENV REACT_APP_BACKEND_WS_URL=wss://api.psycholebedenko.online
RUN npm run build