version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend/
    command: >
      sh -c "yes | npx serve -l 3000 -s -n build"
    container_name: frontend
    volumes:
      - /app/node_modules
      - /app/build
      - ./frontend:/app
    ports:
      - "80:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    command: >
      sh -c "python manage.py migrate --run-syncdb &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    container_name: backend
    image: backend-img
    volumes:
      - ./backend:/app
    ports:
      - "81:8000"
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy

  telebot:
    image: backend-img
    container_name: telebot
    env_file:
      - .env.prod
    command: >
      sh -c "python manage.py runbot"
    depends_on:
      - backend

  db:
    image: postgres:15.4
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 20s
      timeout: 10s
      retries: 3

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    container_name: rabbitmq
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=+sbwt none +sbwtdcpu none +sbwtdio none
    ports:
      - "5672:5672"

  worker:
    image: backend-img
    container_name: worker
    env_file:
      - .env.prod
    command: >
      sh -c "celery -A app worker -l info 
      --without-heartbeat --without-gossip --without-mingle"
    depends_on:
      - rabbitmq

  celery-beat:
    image: backend-img
    container_name: celery-beat
    env_file:
      - .env.prod
    command: >
      sh -c "celery -A app beat -l info"
    depends_on:
      - rabbitmq

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server
    hostname: redis
    volumes:
      - ./redis:/var/lib/redis
    ports:
      - 6379:6379