version: '3.8'

services:
  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate --run-syncdb &&
      python manage.py runserver 0.0.0.0:8000"
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "80:8000"
    environment:
      - DEBUG=1
      - TELEGRAM_BOT_API_KEY=6159160252:AAF1wkp3scOkCDnOoah8y_s9IcYIhWwxlUY
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    command: >
      sh -c "npm start"
    volumes:
      - ./frontend:/app
      - ./frontend:/node_moduless
    ports:
      - "81:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 10