# Generated by Django 4.2.2 on 2023-08-08 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='appointment',
        ),
    ]
