# Generated by Django 4.2.2 on 2023-08-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_schedule_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
