# Generated by Django 4.2.2 on 2023-10-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='photo_url',
            field=models.URLField(blank=True, default='https://psycholebedenko-backend.s3.amazonaws.com/user_photo.jpeg', max_length=512, null=True),
        ),
    ]
