# Generated by Django 4.2.2 on 2024-07-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_telegramuser_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='photo_url',
            field=models.URLField(blank=True, default='https://psycholebedenko-bucket.s3.eu-central-1.amazonaws.com/user_photo.jpeg', max_length=512, null=True),
        ),
    ]
