# Generated by Django 4.2.2 on 2023-07-01 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_telegramuser_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='user_permissions',
        ),
    ]
