# Generated by Django 4.2.2 on 2023-07-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_telegramuser_is_active_telegramuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
