# Generated by Django 4.2.2 on 2023-07-02 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_telegramuser_groups_telegramuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
