# Generated by Django 4.2.2 on 2023-08-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
