# Generated by Django 4.2.2 on 2023-07-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
