# Generated by Django 4.2.2 on 2023-08-16 08:14

import appointment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_schedule_date'),
        ('appointment', '0004_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(blank=True, default=appointment.models.set_default_address, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.schedule'),
        ),
    ]
