# Generated by Django 4.0 on 2023-06-27 23:16

import appointment.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.TextField(default=appointment.models.set_default_title),
        ),
    ]
