# Generated by Django 4.0 on 2023-06-27 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointment_created_at_alter_appointment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
